version: '3.7'
services:
  web:
    build: .
    container_name: nodejs_api
    restart: unless-stopped
    command: /bin/sh -c 'nodemon -e js,html index.js'
    ports:
      - 9001:9001
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      # NODE_ENV: dev
      VIRTUAL_HOST: app1.example.com
      VIRTUAL_PORT: 9001
    network_mode: bridge
    # external_links:
    #   - mysql
