version: '3.7'
services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    command: /bin/sh -c 'nodemon -e js,html index.js'
    ports:
      - 9008:9008
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      # NODE_ENV: dev
      VIRTUAL_HOST: api.example.com
      VIRTUAL_PORT: 9008
    network_mode: bridge
    external_links:
      - mysql
